import { Container, Badge, Card } from "../../ui";
import styles from "./AILinter.module.css";

export function AILinter() {
  return (
    <section className={styles.section}>
      <Container size='xl'>
        <div className={styles.grid}>
          <div className={styles.preview}>
            <Card variant='elevated' padding='md' className={styles.editorCard}>
              <div className={styles.editor}>
                <div className={styles.lineNumbers}>
                  {[1, 2, 3, 4, 5, 6, 7, 8].map((n) => (
                    <span key={n}>{n}</span>
                  ))}
                </div>
                <div className={styles.code}>
                  <p>📊 Repository Analysis</p>
                  <p>&nbsp;</p>
                  <p>Files: <span className={styles.warning}>248</span></p>
                  <p className={styles.errorLine}>
                    Lines: <span className={styles.error}>12,543</span>
                  </p>
                  <p>Tech Stack: React, TypeScript</p>
                  <p>&nbsp;</p>
                  <p>
                    Dependencies: <span className={styles.warning}>42</span>
                  </p>
                  <p>Code Health: ⭐⭐⭐⭐⭐</p>
                </div>
              </div>
              <div className={styles.linterPopup}>
                <div className={styles.popupHeader}>
                  <span className={styles.warningIcon}>💡</span>
                  <span>AI Insight</span>
                </div>
                <p className={styles.popupText}>
                  Well-structured React project with modern TypeScript
                </p>
                <button className={styles.fixButton}>View Details</button>
              </div>
            </Card>
          </div>

          <div className={styles.content}>
            <div className={styles.badges}>
              <Badge variant='primary'>NEW</Badge>
              <Badge variant='secondary'>Insights</Badge>
            </div>
            <h2 className={styles.title}>Analysis Dashboard</h2>
            <p className={styles.description}>
              Visualize repository insights with comprehensive dashboards 
              generated by AI analysis.
            </p>

            <ul className={styles.features}>
              <li>
                <span className={styles.checkIcon}>✓</span>
                Code metrics & statistics
              </li>
              <li>
                <span className={styles.checkIcon}>✓</span>
                Architecture diagrams
              </li>
              <li>
                <span className={styles.checkIcon}>✓</span>
                Dependency analysis
              </li>
              <li>
                <span className={styles.checkIcon}>✓</span>
                AI-generated insights
              </li>
            </ul>
          </div>
        </div>

        <div className={styles.cards}>
          <Card variant='outlined' padding='lg' className={styles.featureCard}>
            <div className={styles.featureIcon}>📊</div>
            <h3 className={styles.featureTitle}>Real-Time Metrics</h3>
            <p className={styles.featureDesc}>
              Track code complexity, file count, dependencies, and tech stack 
              in an intuitive visual interface.
            </p>
          </Card>

          <Card variant='outlined' padding='lg' className={styles.featureCard}>
            <div className={styles.featureIcon}>👩🏻‍💻</div>
            <h3 className={styles.featureTitle}>Learning Resources</h3>
            <p className={styles.featureDesc}>
              AI-generated study materials, tutorials, and personalized 
              learning paths to master the repository's technologies.
            </p>
          </Card>
        </div>
      </Container>
    </section>
  );
}

export default AILinter;
